# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Find My Pet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Find My Pet
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Core'
  pod 'FirebaseFirestoreSwift'

  target 'Find My PetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Find My PetUITests' do
    # Pods for testing
  end

end
